🐛 Fix for hard-coded parsing bug that made touchedFiles undefined.
pabo/jest-enforce pull request #3
Opened 2018-03-15 18:31 UTC by jamesarmenta

2018-05-08 19:03 UTC, pabo requested changes
- I made the comments on the built version instead of the source by mistake

- is this backwards compatible and can be patch bump?

- open the PR against `next` branch

2018-05-08 19:03 UTC, pabo commented on build/bundle.js
> +  var res = [];
`var` ?!

2018-05-08 19:03 UTC, pabo commented on build/bundle.js
> +  if (_has(obj, key)) return [obj[key]];
```
if (_has(obj, key)) {
  return [obj[key]];
}
```

2018-05-08 19:03 UTC, pabo commented on build/bundle.js
> +    if (typeof v == 'object' && (v = deepFindKey(v, key)).length) res.push.apply(res, v);
prefer arrow function

`==`?!

```
if (blah) {
  foo;
}
```

2018-05-08 19:03 UTC, pabo commented on .gitignore
> -build/
why check this in to git?

2018-05-08 22:49 UTC, jamesarmenta commented on build/bundle.js
> +  var res = [];
can you tell i found this online

2018-05-08 23:46 UTC, jamesarmenta commented on build/bundle.js
> +  if (_has(obj, key)) return [obj[key]];
This is because it was minified

2018-05-21 20:13 UTC, pabo approved these changes

2018-05-21 20:21 UTC, merged